### PR TITLE
Remove dependency on lyaml

### PR DESCRIPTION
**Pull request by davvil**
Following #19

Instead of parsing the yaml directly we transform it into json via yq and use neovim's native json parsing.

Removes the dependency of lua rocks, thus making installation easier for lazy.

### CODE REVIEW

**Comment by davvil** [comment]
I recently switched to lazy and it was a bummer to have to drop this plugin. I saw #19 and it seemed easy enough to give it a try :-)

I do not know the code, I basically grepped for lyaml and that's where I changed things. It seems to work fine on my system, and AFAICT there are no further dependencies. As a more general approach we could even allow for other conversion tools apart from `yq`, i.e. parametrize with `json_converter` or similar which defaults to `yq -oj`.

I didn't touch the documentation.

**Comment by jghauser** [comment]
Wow, this is great! :heart: I'm away for a few days, but once I get back in a week, this is gonna be the first thing I look at!

**Comment by jghauser** [comment]
@davvil, could you share the lazy config with which you installed papis.nvim. I would like to add it to the readme to complement the instructions for packer.

**Comment by davvil** [comment]
Sure. It's actually pretty similar to the packer one (by design of lazy). I basically removed the `rocks` line and the `after` one, as this should be automatically detected by lazy.

```
  {
    "jghauser/papis.nvim",
    dependencies = {
      "kkharji/sqlite.lua",
      "nvim-lua/plenary.nvim",
      "MunifTanjim/nui.nvim",
      "nvim-treesitter/nvim-treesitter",
    },
    config = function()
      require("papis").setup({
      -- Your configuration goes here
      })
    end,
  }
```

**Comment by jghauser** [comment]
Thanks a lot for this! I've added a check to see if the executable exists and updated the docs. I think this will be easier to maintain going forward than depending on `lyaml`.

**Pull request merged**
